_extends: .github

repository:
  name: nightwatch-accessibility
  description: nightwatch-accessibility
  topics: nightwatch,accessibility,axe
  homepage: https://github.com/ahmadnassri/nightwatch-accessibility
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
