language: node_js

node_js:
 - 7
 - 6
 - 4

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

after_success:
  - npm install --only=production semantic-release

deploy:
  skip_cleanup: true
  provider: script
  script: semantic-release pre && npm publish && semantic-release post || true

  on:
    branch: master
    node: 7

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - /^greenkeeper\/.+/
